"""add vendor notifications and bg document path

Revision ID: c9c5c310db32
Revises: 8e746c5519ad
Create Date: 2026-07-22 17:58:10.334923
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c9c5c310db32'
down_revision: str | None = '8e746c5519ad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_notifications',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_notifications_project_id'), 'vendor_notifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_vendor_notifications_vendor_id'), 'vendor_notifications', ['vendor_id'], unique=False)
    op.add_column('projects', sa.Column('bg_document_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'bg_document_path')
    op.drop_index(op.f('ix_vendor_notifications_vendor_id'), table_name='vendor_notifications')
    op.drop_index(op.f('ix_vendor_notifications_project_id'), table_name='vendor_notifications')
    op.drop_table('vendor_notifications')
    # ### end Alembic commands ###
