"""add sppb documents, drop project sppb number/date

Revision ID: 64148bb5f7d7
Revises: a0fd6b09aced
Create Date: 2026-07-23 08:48:35.162548
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '64148bb5f7d7'
down_revision: str | None = 'a0fd6b09aced'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sppb',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_no', 'year', name='uq_sppb_sequence_per_year')
    )
    op.create_index(op.f('ix_sppb_number'), 'sppb', ['number'], unique=True)
    op.create_index(op.f('ix_sppb_year'), 'sppb', ['year'], unique=False)
    op.create_table('sppb_items',
    sa.Column('sppb_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity_delivered', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sppb_id'], ['sppb.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sppb_items_sppb_id'), 'sppb_items', ['sppb_id'], unique=False)
    op.drop_column('projects', 'sppb_date')
    op.drop_column('projects', 'sppb_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sppb_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('sppb_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sppb_items_sppb_id'), table_name='sppb_items')
    op.drop_table('sppb_items')
    op.drop_index(op.f('ix_sppb_year'), table_name='sppb')
    op.drop_index(op.f('ix_sppb_number'), table_name='sppb')
    op.drop_table('sppb')
    # ### end Alembic commands ###
