"""add user last seen notifications at

Revision ID: 7f91cf1ff16f
Revises: 64148bb5f7d7
Create Date: 2026-07-23 11:47:57.889699
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7f91cf1ff16f'
down_revision: str | None = '64148bb5f7d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_notifications_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_notifications_at')
    # ### end Alembic commands ###
