"""add project timeline

Revision ID: 8e746c5519ad
Revises: 7ad1f05f2fd6
Create Date: 2026-07-22 16:49:21.847585
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8e746c5519ad'
down_revision: str | None = '7ad1f05f2fd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_timeline_events',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('BIDDING', 'PENGUMUMAN_MENANG', 'SPK', 'SPPB', 'PENGERJAAN', 'BARANG_LENGKAP', 'FINISHED', name='project_stage', native_enum=False, length=40), nullable=False),
    sa.Column('actor_role', sa.Enum('RS', 'VENDOR', 'BANK_MANDIRI', name='user_role', native_enum=False, length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_timeline_events_project_id'), 'project_timeline_events', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('stage', sa.Enum('BIDDING', 'PENGUMUMAN_MENANG', 'SPK', 'SPPB', 'PENGERJAAN', 'BARANG_LENGKAP', 'FINISHED', name='project_stage', native_enum=False, length=40), nullable=True))
    op.execute("UPDATE projects SET stage = 'BIDDING' WHERE stage IS NULL")
    op.execute(
        "UPDATE projects SET stage = 'PENGUMUMAN_MENANG' "
        "WHERE winning_vendor_id IS NOT NULL AND stage = 'BIDDING'"
    )
    op.execute(
        "UPDATE projects SET stage = 'SPK' "
        "WHERE id IN (SELECT project_id FROM spk WHERE status = 'ISSUED') AND stage <> 'SPK'"
    )
    op.alter_column('projects', 'stage', nullable=False)
    op.add_column('projects', sa.Column('bg_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('projects', sa.Column('bg_valid_until', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('bg_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('sppb_number', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('sppb_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('work_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('goods_reported_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('goods_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('invoice_number', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_projects_stage'), 'projects', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_stage'), table_name='projects')
    op.drop_column('projects', 'finished_at')
    op.drop_column('projects', 'invoice_date')
    op.drop_column('projects', 'invoice_number')
    op.drop_column('projects', 'goods_confirmed_at')
    op.drop_column('projects', 'goods_reported_at')
    op.drop_column('projects', 'work_started_at')
    op.drop_column('projects', 'sppb_date')
    op.drop_column('projects', 'sppb_number')
    op.drop_column('projects', 'bg_submitted_at')
    op.drop_column('projects', 'bg_valid_until')
    op.drop_column('projects', 'bg_amount')
    op.drop_column('projects', 'stage')
    op.drop_index(op.f('ix_project_timeline_events_project_id'), table_name='project_timeline_events')
    op.drop_table('project_timeline_events')
    # ### end Alembic commands ###
