"""initial schema

Revision ID: 0f635440302f
Revises: 
Create Date: 2026-07-22 11:33:10.540469
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0f635440302f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('npwp', sa.String(length=25), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_type', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('bank', sa.Enum('MANDIRI', 'LAINNYA', name='bank_group', native_enum=False, length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('bank_account_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'NEED_VERIFICATION', 'VERIFIED', 'REJECTED', name='vendor_status', native_enum=False, length=20), nullable=False),
    sa.Column('verification_step', sa.Integer(), nullable=False),
    sa.Column('documents', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('financial_score', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('performance_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_company_name'), 'vendors', ['company_name'], unique=False)
    op.create_index(op.f('ix_vendors_npwp'), 'vendors', ['npwp'], unique=True)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('BARANG', 'JASA', 'KONSTRUKSI', 'KONSULTANSI', name='project_type', native_enum=False, length=20), nullable=False),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('hps', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ONGOING', 'COMPLETED', 'CANCELLED', name='project_status', native_enum=False, length=20), nullable=False),
    sa.Column('bank', sa.Enum('MANDIRI', 'LAINNYA', name='bank_group', native_enum=False, length=20), nullable=True),
    sa.Column('winning_vendor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['winning_vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('project_vendors',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'vendor_id')
    )
    op.create_table('spk',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('work_description', sa.Text(), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('penalty_clause', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('signatory_name', sa.String(length=255), nullable=False),
    sa.Column('signatory_position', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'CANCELLED', name='spk_status', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_no', 'year', name='uq_spk_sequence_per_year')
    )
    op.create_index(op.f('ix_spk_number'), 'spk', ['number'], unique=True)
    op.create_index(op.f('ix_spk_status'), 'spk', ['status'], unique=False)
    op.create_index(op.f('ix_spk_year'), 'spk', ['year'], unique=False)
    op.create_table('spk_items',
    sa.Column('spk_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spk_id'], ['spk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spk_items_spk_id'), 'spk_items', ['spk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spk_items_spk_id'), table_name='spk_items')
    op.drop_table('spk_items')
    op.drop_index(op.f('ix_spk_year'), table_name='spk')
    op.drop_index(op.f('ix_spk_status'), table_name='spk')
    op.drop_index(op.f('ix_spk_number'), table_name='spk')
    op.drop_table('spk')
    op.drop_table('project_vendors')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_npwp'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_company_name'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
