"""add vendor director_name

Revision ID: 0d8fb17f186d
Revises: 0f635440302f
Create Date: 2026-07-22 12:22:52.337124
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0d8fb17f186d'
down_revision: str | None = '0f635440302f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('director_name', sa.String(length=255), nullable=True))
    op.execute("UPDATE vendors SET director_name = '-' WHERE director_name IS NULL")
    op.alter_column('vendors', 'director_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'director_name')
    # ### end Alembic commands ###
