"""add project participant bid prices

Revision ID: f233ab471c2d
Revises: e7e80fa48e1a
Create Date: 2026-07-22 14:45:23.941081
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f233ab471c2d'
down_revision: str | None = 'e7e80fa48e1a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_vendors', sa.Column('bid_price', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('project_vendors', sa.Column('corrected_price', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('project_vendors', sa.Column('negotiated_price', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('project_vendors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('project_vendors', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_vendors', 'updated_at')
    op.drop_column('project_vendors', 'created_at')
    op.drop_column('project_vendors', 'negotiated_price')
    op.drop_column('project_vendors', 'corrected_price')
    op.drop_column('project_vendors', 'bid_price')
    # ### end Alembic commands ###
