"""add vendor category classification

Revision ID: 7ad1f05f2fd6
Revises: 2b2acc4e2fdb
Create Date: 2026-07-22 16:12:58.232811
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7ad1f05f2fd6'
down_revision: str | None = '2b2acc4e2fdb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('vendor_category', sa.Enum('OPERASIONAL', 'PENGADAAN', 'CLEANING_SERVICE', name='vendor_category', native_enum=False, length=30), nullable=True))
    op.add_column('vendors', sa.Column('category', sa.Enum('OPERASIONAL', 'PENGADAAN', 'CLEANING_SERVICE', name='vendor_category', native_enum=False, length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'category')
    op.drop_column('projects', 'vendor_category')
    # ### end Alembic commands ###
