"""add spk signed document path

Revision ID: a0fd6b09aced
Revises: c9c5c310db32
Create Date: 2026-07-22 19:04:06.598404
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a0fd6b09aced'
down_revision: str | None = 'c9c5c310db32'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spk', sa.Column('signed_document_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spk', 'signed_document_path')
    # ### end Alembic commands ###
