"""add user role and vendor link

Revision ID: 2b2acc4e2fdb
Revises: f233ab471c2d
Create Date: 2026-07-22 15:38:47.628617
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2b2acc4e2fdb'
down_revision: str | None = 'f233ab471c2d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('RS', 'VENDOR', 'BANK_MANDIRI', name='user_role', native_enum=False, length=20), nullable=True))
    op.execute("UPDATE users SET role = 'RS' WHERE role IS NULL")
    op.alter_column('users', 'role', nullable=False)
    op.add_column('users', sa.Column('vendor_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'users', ['vendor_id'])
    op.create_foreign_key(None, 'users', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'vendor_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
